# fly.toml app configuration file generated for garage35 on 2025-10-15T17:06:01+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'garage35'
primary_region = 'arn'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0


[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
